### ISSUE TITLE
Update to meta description for pressbooks.directory 

### ISSUE THREAD

**Issue by Jennonite** [pressbooks/pressbooks-book-directory-fe#1109]
The current meta description for pressbooks.directory is out of date. It says we have 2,500 books, but we're close to 7,000 now. There are also some other language updates we'd like to make

The current meta description can be found here:
https://github.com/pressbooks/pressbooks-book-directory-fe/blob/e51dadbdc4ca249b0a7ee87c7664becd958fcfc3/index.html#L7 

We would like to propose a change so that this text is the same as the homepage of pressbooks.directory, and that the numbers are updated automatically like they are on the homepage. The updated description would be:

"Pressbooks Directory is a free, searchable catalog that includes 6,761 open access books published by 178 organizations and networks using Pressbooks."

(but this number changes every time a new book is added to the Directory)

If it's not possible to automatically update the numbers, we'd like to update to the text below:

"Pressbooks Directory is a free, searchable catalog that includes over 6,000 open access books published by hundreds of organizations and networks using Pressbooks."

**Comment by SteelWagstaff** [comment]
Additional notes for developers. We already have a dynamically updated component in the Vue component used at the top of the home page: https://github.com/pressbooks/pressbooks-book-directory-fe/blob/e51dadbdc4ca249b0a7ee87c7664becd958fcfc3/src/components/PbWelcomeHeader.vue#L11-L14
which uses these computed values:
https://github.com/pressbooks/pressbooks-book-directory-fe/blob/e51dadbdc4ca249b0a7ee87c7664becd958fcfc3/src/components/PbWelcomeHeader.vue#L47-L60

**Comment by cmurtagh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks-book-directory-fe/1109?planning-poker) with Zenhub @arzola @fdalcin @ho-man-chan @MichelleWeremczuk @richard015ar @tw77

**Comment by cmurtagh** [comment]
Line updated using the static version in above PR.
