### ISSUE TITLE
Default image for unavailable book covers

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks-book-directory-fe#180]
In some cases book covers are not available to display in the Directory, reasons could be:
- Image is not longer available in the external server
- Image is from HTTP instead HTTPS - CORS issue in Chrome
- Image is unreachable 

When the image is not available, the cards now look like:
![Screenshot from 2021-02-10 11-36-10](https://user-images.githubusercontent.com/13248424/107540660-4876a900-6b94-11eb-8ecf-29618eedec0e.png)

Validate the image availability before displaying it. If it is not possible to display the image, use a default cover image as a fallback. Use new cover image once available. See https://github.com/pressbooks/ideas/issues/365

See https://vuetifyjs.com/en/api/v-img for implementation.

**Comment by SteelWagstaff** [comment]
Tested and working as expected in dev.pressbooks.directory.
