### ISSUE TITLE
Social icons in footer don't match marketing site

### ISSUE THREAD

**Issue by SevenSidedSquare** [pressbooks/pressbooks-book-directory-fe#283]
In V2 directory, they look like this:

![Screen Shot 2021-05-14 at 12 00 03 PM](https://user-images.githubusercontent.com/27644125/118297329-fc494680-b4ab-11eb-9cb1-06cc967cdad7.png)

On the marketing site they look like this:

![Screen Shot 2021-05-14 at 12 01 43 PM](https://user-images.githubusercontent.com/27644125/118297485-36b2e380-b4ac-11eb-884c-594f00daf93d.png)

The V2 should look like the marketing site.

**Comment by SteelWagstaff** [comment]
Resolved by #836
