### ISSUE TITLE
Add business metric (most clicked) to index and define in custom ranking

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book-directory-fe#321]
Creating business metrics based on Algolia events can help us customize the ranking of books in the directory. Custom ranking (https://www.algolia.com/doc/guides/managing-results/must-do/custom-ranking/#custom-ranking) is second only to searchable attributes in importance, and is critical to ranking and relevance because it gives us direct control over every set of results.

Now that we're collecting 'Insights API' information, we want to use this to improve/refine book dispay order/ranking in the default index. We should more heavily weight the most visited books. Research how to do this and make a recommendation.

- [ ] Create a Lambda function which runs a partial update for a book record when the 'Book Opened' conversion event is triggered. The goal is to keep a 'count' of # of times the book has been opened all time. So increment an integer.

**Comment by arzola** [comment]
I think is easy to write an small lambda function just to update a record, or adding a method into the fetcher and expose that function using the api gateway

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html

Right now we have a public endpoint for the fetcher https://3tm1nc05q0.execute-api.ca-central-1.amazonaws.com/dev/api/books/update I think we could use a new REST endpoint like `https://3tm1nc05q0.execute-api.ca-central-1.amazonaws.com/dev/api/books/visit/objectID` 

If we use the fetcher code we don't have to create a new serverless function and setup we can reuse all of the fetcher setup, just adding a new method to increase visits when the endpoint is requested

But maybe it could be a good idea to discuss this with Ho Man

**Comment by arzola** [comment]
I created this PR https://github.com/pressbooks/book-directory-fetcher/pull/151 that will allow us to have a public endpoint like: `https://3tm1nc05q0.execute-api.ca-central-1.amazonaws.com/dev/api/books/visit` that is going to receive the objectID as a book_id to increase the visits count

This method is safe becase only increase the clickCount value and don't allow to change any other book property in algolia

**Comment by fdalcin** [comment]
Tested on dev and works as expected
