### ISSUE TITLE
Update internal documentation

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks-book-directory-fe#342]
Update the internal documentation: https://docs.google.com/document/d/1F82PSJKeufpKp8bGrDifjPxGo2x6tKD-HJpTsuadCeg/edit#heading=h.6bhx1gux5yio and https://docs.google.com/document/d/1SNf7jIelkXwzzAxEbGSjEL59GMDeh3o3wH7myY3LfBM/edit with correct details about the new pipeline, workflow, tech stack, and Algolia index configuration.

**Comment by SteelWagstaff** [comment]
Updatedhttps://docs.google.com/document/d/1F82PSJKeufpKp8bGrDifjPxGo2x6tKD-HJpTsuadCeg and retired https://docs.google.com/document/d/1SNf7jIelkXwzzAxEbGSjEL59GMDeh3o3wH7myY3LfBM/edit after moving relevant content to first doc.
