### ISSUE TITLE
Lazy load all book cover images

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book-directory-fe#352]
Add load="lazy" to all book cover images in page results to improve page load time and performance. We do not need to focus on supporting IE 11 and earlier.

See https://web.dev/lazy-loading-images/ + https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading

Implementation ideas: https://css-tricks.com/the-complete-guide-to-lazy-loading-images/ + https://css-tricks.com/lazy-loading-images-with-vue-js-directives-and-intersection-observer/ + https://www.npmjs.com/package/vue-lazyload + https://vueschool.io/articles/vuejs-tutorials/lazy-loading-and-code-splitting-in-vue-js/

**Comment by fdalcin** [comment]
Tested on staging/dev and works as expected
