### ISSUE TITLE
Improve meta description

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book-directory-fe#382]
Current site meta for Production Directory is included below:
```
     <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="description" content="Use the Pressbooks Directory to find and adapt thousands of free textbooks and other OER published with the Pressbooks Authoring & Editing platform.">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">  
      <meta name="robots" content="index, follow">    
      <title>Pressbooks Directory</title>
 ```
Steel has asked Leigh and Travis for their input on preferred copy.

See https://ahrefs.com/blog/meta-description/ for some helpful advice for writing good meta descriptions. Additional reading:  https://developers.google.com/search/docs/advanced/crawling/special-tags + https://ahrefs.com/blog/seo-meta-tags/

**Comment by LeighKP** [comment]
Hi @SteelWagstaff

I did some light keyword research and put together a meta description. Please change the meta description to:

"Pressbooks Directory is the best place to find open educational resources (OER). Search over 2500 open textbooks and other free educational books."

This falls within the 155 character limit, includes a CTA, keywords (both long and short), and uses the active voice, so it should ascribe to common SEO wisdom.
