### ISSUE TITLE
Update footer to match marketing site

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book-directory-fe#402]
Add 'collections hub' & remove 'Accessibility'. See pressbooks.com for reference.

**Comment by fdalcin** [comment]
Tested on staging and dev and works as expected.
There is a new link called OER Collections Hub and the old Accessibility link is removed.

![image](https://user-images.githubusercontent.com/1761690/132945631-52c2b3fe-47a2-47f2-8a59-ac66dd55a862.png)
