### ISSUE TITLE
Book cover images no longer function as hyperlinks

### ISSUE THREAD

**Issue by SevenSidedSquare** [pressbooks/pressbooks-book-directory-fe#407]
After a [previous feature request](https://github.com/pressbooks/pressbooks-book-directory-fe/issues/173), the book cover image in each book card was turned into a hyperlink leading to the book's home page. Since the site redesign, however, the book covers no longer function as links.

It would be helpful to restore that functionality as many users instinctively click on the book covers to view the books.

![107434552-e74dc780-6af8-11eb-8dfe-e4dfc1521e82](https://user-images.githubusercontent.com/27644125/132047841-7bd1cc0d-d4f6-4152-8871-1a8a34bf0834.png)

**Comment by richard015ar** [comment]
See: https://github.com/pressbooks/pressbooks-book-directory-fe/blob/dev/src/components/PbBookCover.vue#L1

**Comment by SteelWagstaff** [comment]
Works as expected on staging directory. Ready for release.
