### ISSUE TITLE
Date-picker has a wrong date

### ISSUE THREAD

**Issue by arzola** [pressbooks/pressbooks-book-directory-fe#522]
The new date-picker is showing the local date of a unix epoch time after selecting a date
![Pasted_Image_2022-07-28__10_50_AM](https://user-images.githubusercontent.com/4997549/181567257-1ce70237-881c-4ab7-91bb-ab9517cef705.png)

Possible solutions:
1. check the PB date picker to see if we can resolve this ourselves
2. Find a date picker that works as expected and supports Vue3
3. Wait for component library to fix upstream issue
4. Build our own component (not preferred)

**Comment by arzola** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks-book-directory-fe/522?planning-poker) with ZenHub @fdalcin @richard015ar @SteelWagstaff

**Comment by arzola** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks-book-directory-fe/522?planning-poker) with ZenHub @MichelleWeremczuk @SevenSidedSquare

**Comment by arzola** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks-book-directory-fe/522?planning-poker) with ZenHub @cmurtagh

**Comment by arzola** [comment]
https://github.com/Vuepic/vue-datepicker/issues/95#issuecomment-1195259737
https://github.com/Vuepic/vue-datepicker/issues/66#issuecomment-1151470513

**Comment by SteelWagstaff** [comment]
Upstream release scheduled for August 1 :tada:

**Comment by SteelWagstaff** [comment]
https://github.com/Vuepic/vue-datepicker/releases/tag/v3.4.0

**Comment by SteelWagstaff** [comment]
Merged to front end repo: https://github.com/pressbooks/pressbooks-book-directory-fe/pull/529. Can be tested on https://dev.pressbooks.directory & https://staging.pressbooks.directory

**Comment by arzola** [comment]
We need to change the utc parameter to `preserve`

**Comment by richard015ar** [comment]
@arzola will present this one on sprint review (in staging probably).
