### ISSUE TITLE
Update to latest supported Node version

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book-directory-fe#923]
Node 20 is the current release, with 18 in active support, and 16 in maintenance only: https://github.com/nodejs/release#release-schedule. This project currently requires Node 16.16: https://github.com/pressbooks/pressbooks-book-directory-fe/blob/dev/.nvmrc. We should bump version of Node supported and update build & test matrices.

**Comment by arzola** [comment]
This was solved on https://github.com/pressbooks/pressbooks-book-directory-fe/pull/1112
